-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2023-05-11 22:16:06 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE


DROP TABLE animal CASCADE CONSTRAINTS;
DROP TABLE cidade CASCADE CONSTRAINTS;
DROP TABLE consulta CASCADE CONSTRAINTS;
DROP TABLE endereco CASCADE CONSTRAINTS;
DROP TABLE especialidade CASCADE CONSTRAINTS;
DROP TABLE especialidade_veterinario CASCADE CONSTRAINTS;
DROP TABLE especie CASCADE CONSTRAINTS;
DROP TABLE horario CASCADE CONSTRAINTS;
DROP TABLE raca CASCADE CONSTRAINTS;
DROP TABLE tutor CASCADE CONSTRAINTS;
DROP TABLE veterinario CASCADE CONSTRAINTS;

CREATE TABLE animal (
    id_animal      NUMBER(10) NOT NULL,
    nome           VARCHAR2(255) NOT NULL,
    dt_nascimento  DATE NOT NULL,
    raca_nm_raca   VARCHAR2(50 CHAR) NOT NULL,
    tutor_id_tutor NUMBER(10) NOT NULL
);

ALTER TABLE animal ADD CONSTRAINT animal_pk PRIMARY KEY ( id_animal );

CREATE TABLE cidade (
    cidade VARCHAR2(60 CHAR) NOT NULL,
    estado VARCHAR2(2 CHAR) NOT NULL
);

ALTER TABLE cidade ADD CONSTRAINT cidade_pk PRIMARY KEY ( cidade,
                                                          estado );

CREATE TABLE consulta (
    id_consulta                    NUMBER(10) 
     NOT NULL,
    animal_id_animal               NUMBER(10) NOT NULL,
    tutor_id_tutor                 NUMBER(10) NOT NULL,
    veterinario_id_veterinario     NUMBER(10) NOT NULL,
    especialidade_nm_especialidade VARCHAR2(50 CHAR) NOT NULL,
    dt_consulta                    DATE NOT NULL
);

CREATE UNIQUE INDEX animal_ix ON
    consulta (
        animal_id_animal
    ASC );

CREATE UNIQUE INDEX tutor__ix ON
    consulta (
        tutor_id_tutor
    ASC );

CREATE UNIQUE INDEX especialidade_ix ON
    consulta (
        especialidade_nm_especialidade
    ASC );

ALTER TABLE consulta ADD CONSTRAINT consulta_pk PRIMARY KEY ( id_consulta );

CREATE TABLE endereco (
    id_endereco    NUMBER(10) NOT NULL,
    logradouro     VARCHAR2(100 CHAR) NOT NULL,
    numero         NUMBER(5) NOT NULL,
    complemento    VARCHAR2(10),
    bairro         VARCHAR2(50 CHAR) NOT NULL,
    cidade_cidade  VARCHAR2(60 CHAR) NOT NULL,
    cidade_estado  VARCHAR2(2 CHAR) NOT NULL,
    tutor_id_tutor NUMBER(10) NOT NULL
);

CREATE UNIQUE INDEX endereco__idx ON
    endereco (
        tutor_id_tutor
    ASC );

ALTER TABLE endereco ADD CONSTRAINT endereco_pk PRIMARY KEY ( id_endereco );

CREATE TABLE especialidade (
    nm_especialidade VARCHAR2(50 CHAR) NOT NULL,
    duracao_consulta NUMBER(3) NOT NULL
);

ALTER TABLE especialidade ADD CONSTRAINT especialidade_pk PRIMARY KEY ( nm_especialidade );

CREATE TABLE especialidade_veterinario (
    id_veterinario   NUMBER(10) NOT NULL,
    nm_especialidade VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE especialidade_veterinario ADD CONSTRAINT especialidade_vet_pk PRIMARY KEY ( id_veterinario,
                                                                                        nm_especialidade );

CREATE TABLE especie (
    nm_especie VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE especie ADD CONSTRAINT especie_pk PRIMARY KEY ( nm_especie );

CREATE TABLE horario (
    dia_semana                 VARCHAR2(7 CHAR) NOT NULL,
    inicio                     DATE NOT NULL,
    fim                        DATE NOT NULL,
    veterinario_id_veterinario NUMBER(10) NOT NULL
);

ALTER TABLE horario ADD CONSTRAINT horario_pk PRIMARY KEY ( veterinario_id_veterinario,
                                                            dia_semana );

CREATE TABLE raca (
    nm_raca            VARCHAR2(50 CHAR) NOT NULL,
    especie_nm_especie VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE raca ADD CONSTRAINT raca_pk PRIMARY KEY ( nm_raca );

CREATE TABLE tutor (
    id_tutor    NUMBER(10) NOT NULL,
    nome        VARCHAR2(255 CHAR) NOT NULL,
    nr_telefone NUMBER(10),
    nr_celular  NUMBER(11) NOT NULL
);

ALTER TABLE tutor ADD CONSTRAINT tutor_pk PRIMARY KEY ( id_tutor );

CREATE TABLE veterinario (
    id_veterinario NUMBER(10) NOT NULL,
    nome           VARCHAR2(255 CHAR) NOT NULL,
    nr_crmv        VARCHAR2(9 CHAR) NOT NULL
);

ALTER TABLE veterinario ADD CONSTRAINT veterinario_pk PRIMARY KEY ( id_veterinario );

ALTER TABLE veterinario ADD CONSTRAINT veterinario_nr_crmv_un UNIQUE ( nr_crmv );

ALTER TABLE consulta
    ADD CONSTRAINT animal_fk FOREIGN KEY ( animal_id_animal )
        REFERENCES animal ( id_animal );

ALTER TABLE animal
    ADD CONSTRAINT animal_raca_fk FOREIGN KEY ( raca_nm_raca )
        REFERENCES raca ( nm_raca );

ALTER TABLE animal
    ADD CONSTRAINT animal_tutor_fk FOREIGN KEY ( tutor_id_tutor )
        REFERENCES tutor ( id_tutor );

ALTER TABLE consulta
    ADD CONSTRAINT consulta_fk FOREIGN KEY ( veterinario_id_veterinario )
        REFERENCES veterinario ( id_veterinario );

ALTER TABLE endereco
    ADD CONSTRAINT endereco_cidade_fk FOREIGN KEY ( cidade_cidade,
                                                    cidade_estado )
        REFERENCES cidade ( cidade,
                            estado );

ALTER TABLE endereco
    ADD CONSTRAINT endereco_tutor_fk FOREIGN KEY ( tutor_id_tutor )
        REFERENCES tutor ( id_tutor );

ALTER TABLE especialidade_veterinario
    ADD CONSTRAINT especialidade_fk FOREIGN KEY ( nm_especialidade )
        REFERENCES especialidade ( nm_especialidade );

ALTER TABLE consulta
    ADD CONSTRAINT especialidade_fkv2 FOREIGN KEY ( especialidade_nm_especialidade )
        REFERENCES especialidade ( nm_especialidade );

ALTER TABLE horario
    ADD CONSTRAINT horario_veterinario_fk FOREIGN KEY ( veterinario_id_veterinario )
        REFERENCES veterinario ( id_veterinario );

ALTER TABLE raca
    ADD CONSTRAINT raca_especie_fk FOREIGN KEY ( especie_nm_especie )
        REFERENCES especie ( nm_especie );

ALTER TABLE consulta
    ADD CONSTRAINT tutor_fk FOREIGN KEY ( tutor_id_tutor )
        REFERENCES tutor ( id_tutor );

ALTER TABLE especialidade_veterinario
    ADD CONSTRAINT veterinario_fk FOREIGN KEY ( id_veterinario )
        REFERENCES veterinario ( id_veterinario );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             4
-- ALTER TABLE                             24
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0


